version: "3.8"

services:
  # Web Server Service
  laravel-docker-app:
    container_name: laravel-docker-app
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 9009:80
    depends_on:
      - mysql_db

  # Database server
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9002:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql_db
